- name: Install apache httpd
  apt:
          name: apache2
          state: present

- name: Start apache httpd
  service:
          name: apache2
          state: started

- name: Enable service httpd
  service:
          name: httpd
          enabled: yes
