- name: eb appversion
  become: true
  become_method: sudo
  become_flags: 'su - root "{{ dest_dir }}" -c'
  shell: cd "{{ dest_dir }}" | eb init --region ap-southeast-1 --platform Node.js test_app | eb appversion --create  
  register: appv_output
  tags:
   - ebdeploy
- set_fact: 
      ver_no: "{{ appv_output.stdout | regex_search('app-\\d{6}_\\d{12}')}}"
- debug:
      var: ver_no
    # msg: "{{ appv_output.stdout | regex_search('app-\\d{6}_\\d{12}')}}"
    # msg={{ appv_output.stdout_lines }}

- name: eb deployment to elastic beanstalk
  become: true
  # become_method: sudo
  become_flags: 'su - root "{{ dest_dir }}" -c'
#   # shell: '/opt/cicd_wrappers/files/ebdeploy_wraper.sh'
#   # shell: cd /opt/test1 | git rm -r --cached venv | git commit -m 'Remove the now ignored directory venv' | git push origin master | eb deploy 
  shell: cd "{{ dest_dir }}" | eb deploy Testapp-env -l "{{ ver_no }}"
  register: command_output
  tags:
   - ebdeploy
- debug:
    var: command_output.stdout_lines