- name: Give insecure permissions to an existing file
  file:
    path: "{{ dest_dir }}/.elasticbeanstalk"
    owner: root
    group: root
    mode: '0777'
  tags:
   - chmod_operation

-  name: Give insecure permissions to an existing file
   file:
    path: "{{ dest_dir }}/.elasticbeanstalk/config.yml"
    owner: root
    group: root
    mode: '0777'
   tags:
    - chmod_operation